version: '3'
services:
  proxy:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ../client:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build: ./backend/
    ports:
      - "8080:8080"
