version: '3'
services:
  proxy:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ../client:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    volumes:
      - grafana:/var/lib/grafana
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
  metrics:
    build: ./metrics/
    depends_on:
      - "influxdb"

volumes:
  influxdb:
  grafana:
